// Code generated by scripts/generate-tajweed.mjs from data/tajweed-rules.json. DO NOT EDIT.
package com.quranengine

object TajweedRulesGenerated {
    val ruleOrder: List<String> = listOf("lamShamsiyah", "droppedLetter", "hamzatWaslSilent", "idghamBilaGhunnah", "generalGhunnah", "idghamGhunnah", "ikhfaaLight", "ikhfaaHeavy", "iqlaab", "qalqalah", "tafkhim", "maddNatural", "maddNaturalMiniature", "maddSukoon", "maddNecessary", "maddSeparated", "maddConnected")

    val colors: Map<String, String> = mapOf(
        "lamShamsiyah" to "#B4B4B4",
        "droppedLetter" to "#B4B4B4",
        "hamzatWaslSilent" to "#B4B4B4",
        "idghamBilaGhunnah" to "#B4B4B4",
        "generalGhunnah" to "#45BC73",
        "idghamGhunnah" to "#45BC73",
        "ikhfaaLight" to "#45BC73",
        "ikhfaaHeavy" to "#1FAA94",
        "iqlaab" to "#75B233",
        "qalqalah" to "#78CCF9",
        "tafkhim" to "#3B85C2",
        "maddNatural" to "#B98C2F",
        "maddNaturalMiniature" to "#B98C2F",
        "maddSukoon" to "#E37935",
        "maddNecessary" to "#AE2517",
        "maddSeparated" to "#EB51AA",
        "maddConnected" to "#D9453E"
    )

    val titles: Map<String, String> = mapOf(
        "lamShamsiyah" to "Solar Lam",
        "droppedLetter" to "Written but Not Pronounced",
        "hamzatWaslSilent" to "Joining Hamzah",
        "idghamBilaGhunnah" to "Merge Without Ghunnah",
        "generalGhunnah" to "Shaddah Ghunnah",
        "idghamGhunnah" to "Merge with Ghunnah",
        "ikhfaaLight" to "Hidden Letter (Light)",
        "ikhfaaHeavy" to "Hidden Letter (Heavy)",
        "iqlaab" to "Noon into Meem",
        "qalqalah" to "Bounce Letter",
        "tafkhim" to "Heavy Letter",
        "maddNatural" to "Madd Letters (2 Counts)",
        "maddNaturalMiniature" to "Tiny Madd Marks",
        "maddSukoon" to "Ending Madd",
        "maddNecessary" to "Madd Lazim",
        "maddSeparated" to "Madd Munfasil",
        "maddConnected" to "Madd Muttasil"
    )

    val letterSets: Map<String, List<String>> = mapOf(
        "heavyBaseLetters" to listOf("خ", "ص", "ض", "ط", "ظ", "غ", "ق"),
        "qalqalahLetters" to listOf("ق", "ط", "ب", "ج", "د"),
        "sunLetters" to listOf("ت", "ث", "د", "ذ", "ر", "ز", "س", "ش", "ص", "ض", "ط", "ظ", "ل", "ن"),
        "alifFollowerLetters" to listOf("ا", "ى"),
        "noonTanweenTargetOnlyIdghamLetters" to listOf("ن"),
        "noonTanweenSplitIdghamLetters" to listOf("م", "ي", "و"),
        "noonTanweenSourceOnlyIdghamLetters" to listOf("ل", "ر"),
        "ikhfaaHeavyLetters" to listOf("ص", "ض", "ط", "ظ", "ق"),
        "ikhfaaLightLetters" to listOf("ت", "ث", "ج", "د", "ذ", "ز", "س", "ش", "ف", "ك")
    )

    fun colorForRule(ruleId: String): String? = colors[ruleId]
}
