#!/usr/bin/env node
/**
 * SINGLE SOURCE OF TRUTH → CODE GENERATOR for the tajweed rule catalogue.
 *
 * Reads data/tajweed-rules.json (the master) and regenerates, in every language port, a
 * `tajweed-rules.generated.*` file containing the rule colors, titles, order, and letter sets —
 * plus docs/tajweed-rules-reference.md.
 *
 * Workflow: edit data/tajweed-rules.json, run `node scripts/generate-tajweed.mjs`, done — every
 * language and the reference doc update together. No hand-editing of the generated files.
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const p = (...a) => join(ROOT, ...a);
const master = JSON.parse(await readFile(p("data", "tajweed-rules.json"), "utf-8"));

const cats = [...master.categories].sort((a, b) => a.sortRank - b.sortRank);
const colors = cats.map((c) => [c.id, c.colorHex]);
const titles = cats.map((c) => [c.id, c.englishTitle]);
const order = cats.map((c) => c.id);
const letterSets = Object.entries(master.letterSets ?? {});
const BANNER = "Code generated by scripts/generate-tajweed.mjs from data/tajweed-rules.json. DO NOT EDIT.";

// ---- helpers to emit language-native literals ---------------------------------
const q = (s) => JSON.stringify(s); // safe double-quoted string (handles Arabic + escapes)
const pairs = (arr, l = "{", r = "}", sep = ": ", join = ", ") =>
  `${l}${arr.map(([k, v]) => `${q(k)}${sep}${q(v)}`).join(join)}${r}`;

const targets = [];

// 1. JavaScript -----------------------------------------------------------------
targets.push({
  file: p("packages", "quran-engine-js", "src", "tajweed-rules.generated.js"),
  body: `// @ts-check
// ${BANNER}
export const TAJWEED_RULE_ORDER = ${JSON.stringify(order)};
export const TAJWEED_COLORS = ${JSON.stringify(Object.fromEntries(colors), null, 2)};
export const TAJWEED_TITLES = ${JSON.stringify(Object.fromEntries(titles), null, 2)};
export const TAJWEED_LETTER_SETS = ${JSON.stringify(master.letterSets ?? {}, null, 2)};
export const TAJWEED_MUQATTAAT = ${JSON.stringify(master.muqattaat ?? {}, null, 2)};
/** @param {string} ruleId */
export function colorForRule(ruleId) { return TAJWEED_COLORS[ruleId] ?? null; }
`,
});

// 2. Python ---------------------------------------------------------------------
targets.push({
  file: p("packages", "quran-engine-py", "quran_engine", "tajweed_rules_generated.py"),
  body: `# ${BANNER}
import json

_DATA = json.loads(r'''${JSON.stringify({
    order, colors: Object.fromEntries(colors), titles: Object.fromEntries(titles),
    letterSets: master.letterSets ?? {}, muqattaat: master.muqattaat ?? {},
  })}''')

TAJWEED_RULE_ORDER = _DATA["order"]
TAJWEED_COLORS = _DATA["colors"]
TAJWEED_TITLES = _DATA["titles"]
TAJWEED_LETTER_SETS = _DATA["letterSets"]
TAJWEED_MUQATTAAT = _DATA["muqattaat"]


def color_for_rule(rule_id: str):
    return TAJWEED_COLORS.get(rule_id)
`,
});

// 3. Swift ----------------------------------------------------------------------
{
  const colorLines = colors.map(([k, v]) => `        ${q(k)}: ${q(v)},`).join("\n");
  const titleLines = titles.map(([k, v]) => `        ${q(k)}: ${q(v)},`).join("\n");
  const setLines = letterSets
    .map(([k, arr]) => `        ${q(k)}: [${arr.map(q).join(", ")}],`).join("\n");
  targets.push({
    file: p("packages", "quran-engine-swift", "Sources", "QuranEngine", "TajweedRulesGenerated.swift"),
    body: `// ${BANNER}
import Foundation

public enum TajweedRulesGenerated {
    public static let ruleOrder: [String] = [${order.map(q).join(", ")}]

    public static let colors: [String: String] = [
${colorLines}
    ]

    public static let titles: [String: String] = [
${titleLines}
    ]

    public static let letterSets: [String: [String]] = [
${setLines}
    ]

    public static func color(forRule ruleId: String) -> String? { colors[ruleId] }
}
`,
  });
}

// 4. Kotlin ---------------------------------------------------------------------
{
  const colorLines = colors.map(([k, v]) => `        ${q(k)} to ${q(v)}`).join(",\n");
  const titleLines = titles.map(([k, v]) => `        ${q(k)} to ${q(v)}`).join(",\n");
  const setLines = letterSets
    .map(([k, arr]) => `        ${q(k)} to listOf(${arr.map(q).join(", ")})`).join(",\n");
  targets.push({
    file: p("packages", "quran-engine-kotlin", "src", "main", "kotlin", "com", "quranengine", "TajweedRulesGenerated.kt"),
    body: `// ${BANNER}
package com.quranengine

object TajweedRulesGenerated {
    val ruleOrder: List<String> = listOf(${order.map(q).join(", ")})

    val colors: Map<String, String> = mapOf(
${colorLines}
    )

    val titles: Map<String, String> = mapOf(
${titleLines}
    )

    val letterSets: Map<String, List<String>> = mapOf(
${setLines}
    )

    fun colorForRule(ruleId: String): String? = colors[ruleId]
}
`,
  });
}

// 5. Dart -----------------------------------------------------------------------
{
  const colorLines = colors.map(([k, v]) => `  ${q(k)}: ${q(v)},`).join("\n");
  const titleLines = titles.map(([k, v]) => `  ${q(k)}: ${q(v)},`).join("\n");
  const setLines = letterSets
    .map(([k, arr]) => `  ${q(k)}: [${arr.map(q).join(", ")}],`).join("\n");
  targets.push({
    file: p("packages", "quran-engine-dart", "lib", "src", "tajweed_rules_generated.dart"),
    body: `// ${BANNER}

const List<String> tajweedRuleOrder = [${order.map(q).join(", ")}];

const Map<String, String> tajweedColors = {
${colorLines}
};

const Map<String, String> tajweedTitles = {
${titleLines}
};

const Map<String, List<String>> tajweedLetterSets = {
${setLines}
};

String? colorForRule(String ruleId) => tajweedColors[ruleId];
`,
  });
}

// 6. Go -------------------------------------------------------------------------
{
  const colorLines = colors.map(([k, v]) => `\t${q(k)}: ${q(v)},`).join("\n");
  const titleLines = titles.map(([k, v]) => `\t${q(k)}: ${q(v)},`).join("\n");
  const setLines = letterSets
    .map(([k, arr]) => `\t${q(k)}: {${arr.map(q).join(", ")}},`).join("\n");
  targets.push({
    file: p("packages", "quran-engine-go", "tajweed_rules_generated.go"),
    body: `// ${BANNER}
package quranengine

// TajweedRuleOrder lists rule ids in display (sortRank) order.
var TajweedRuleOrder = []string{${order.map(q).join(", ")}}

// TajweedColors maps a rule id to its hex color.
var TajweedColors = map[string]string{
${colorLines}
}

// TajweedTitles maps a rule id to its English title.
var TajweedTitles = map[string]string{
${titleLines}
}

// TajweedLetterSets holds the trigger-letter groups.
var TajweedLetterSets = map[string][]string{
${setLines}
}

// ColorForRule returns the hex color for a rule id, or "" if unknown.
func ColorForRule(ruleID string) string { return TajweedColors[ruleID] }
`,
  });
}

// 7. Rust -----------------------------------------------------------------------
{
  const colorLines = colors.map(([k, v]) => `    (${q(k)}, ${q(v)}),`).join("\n");
  const titleLines = titles.map(([k, v]) => `    (${q(k)}, ${q(v)}),`).join("\n");
  const setLines = letterSets
    .map(([k, arr]) => `    (${q(k)}, &[${arr.map(q).join(", ")}]),`).join("\n");
  targets.push({
    file: p("packages", "quran-engine-rust", "src", "tajweed_rules_generated.rs"),
    body: `// ${BANNER}
//! Add \`pub mod tajweed_rules_generated;\` to lib.rs to use these constants.

pub const TAJWEED_RULE_ORDER: &[&str] = &[${order.map(q).join(", ")}];

pub const TAJWEED_COLORS: &[(&str, &str)] = &[
${colorLines}
];

pub const TAJWEED_TITLES: &[(&str, &str)] = &[
${titleLines}
];

pub const TAJWEED_LETTER_SETS: &[(&str, &[&str])] = &[
${setLines}
];

pub fn color_for_rule(rule_id: &str) -> Option<&'static str> {
    TAJWEED_COLORS.iter().find(|(k, _)| *k == rule_id).map(|(_, v)| *v)
}
`,
  });
}

// ---- write all language targets ------------------------------------------------
for (const t of targets) {
  await mkdir(dirname(t.file), { recursive: true });
  await writeFile(t.file, t.body, "utf-8");
  console.log("generated", t.file.replace(ROOT + "/", ""));
}

// ---- docs/tajweed-rules-reference.md (generated table) -------------------------
const sections = master.sections ?? [];
let md = `# Tajweed rule reference (generated)

> Generated from [\`data/tajweed-rules.json\`](../data/tajweed-rules.json) by
> \`scripts/generate-tajweed.mjs\`. **Do not edit by hand** — edit the master and regenerate.
> For plain-English explanations of each rule, see [tajweed-rules-explained.md](tajweed-rules-explained.md).

${cats.length} rule categories across ${sections.length} sections.

`;
for (const sec of sections) {
  const inSec = cats.filter((c) => c.section === sec.id);
  md += `## ${sec.title}\n\n`;
  md += `| Rule | Color | Counts | Trigger letters | Meaning |\n|---|---|---|---|---|\n`;
  for (const c of inSec) {
    md += `| **${c.englishTitle}** (${c.transliteration}) — \`${c.id}\` | \`${c.colorHex}\` | ${c.countLabel ?? "—"} | ${c.applicableLetters ? c.applicableLetters.replace(/\|/g, "\\|") : "—"} | ${c.literalMeaning ?? ""} |\n`;
  }
  md += `\n`;
}
md += `## Letter sets\n\n`;
for (const [k, arr] of letterSets) md += `- **${k}**: ${arr.join(" ")}\n`;
await mkdir(p("docs"), { recursive: true });
await writeFile(p("docs", "tajweed-rules-reference.md"), md, "utf-8");
console.log("generated docs/tajweed-rules-reference.md");

console.log(`\nDone. ${targets.length} language files + 1 doc generated from ${cats.length} rules.`);
