// Code generated by scripts/generate-tajweed.mjs from data/tajweed-rules.json. DO NOT EDIT.

const List<String> tajweedRuleOrder = ["lamShamsiyah", "droppedLetter", "hamzatWaslSilent", "idghamBilaGhunnah", "generalGhunnah", "idghamGhunnah", "ikhfaaLight", "ikhfaaHeavy", "iqlaab", "qalqalah", "tafkhim", "maddNatural", "maddNaturalMiniature", "maddSukoon", "maddNecessary", "maddSeparated", "maddConnected"];

const Map<String, String> tajweedColors = {
  "lamShamsiyah": "#B4B4B4",
  "droppedLetter": "#B4B4B4",
  "hamzatWaslSilent": "#B4B4B4",
  "idghamBilaGhunnah": "#B4B4B4",
  "generalGhunnah": "#45BC73",
  "idghamGhunnah": "#45BC73",
  "ikhfaaLight": "#45BC73",
  "ikhfaaHeavy": "#1FAA94",
  "iqlaab": "#75B233",
  "qalqalah": "#78CCF9",
  "tafkhim": "#3B85C2",
  "maddNatural": "#B98C2F",
  "maddNaturalMiniature": "#B98C2F",
  "maddSukoon": "#E37935",
  "maddNecessary": "#AE2517",
  "maddSeparated": "#EB51AA",
  "maddConnected": "#D9453E",
};

const Map<String, String> tajweedTitles = {
  "lamShamsiyah": "Solar Lam",
  "droppedLetter": "Written but Not Pronounced",
  "hamzatWaslSilent": "Joining Hamzah",
  "idghamBilaGhunnah": "Merge Without Ghunnah",
  "generalGhunnah": "Shaddah Ghunnah",
  "idghamGhunnah": "Merge with Ghunnah",
  "ikhfaaLight": "Hidden Letter (Light)",
  "ikhfaaHeavy": "Hidden Letter (Heavy)",
  "iqlaab": "Noon into Meem",
  "qalqalah": "Bounce Letter",
  "tafkhim": "Heavy Letter",
  "maddNatural": "Madd Letters (2 Counts)",
  "maddNaturalMiniature": "Tiny Madd Marks",
  "maddSukoon": "Ending Madd",
  "maddNecessary": "Madd Lazim",
  "maddSeparated": "Madd Munfasil",
  "maddConnected": "Madd Muttasil",
};

const Map<String, List<String>> tajweedLetterSets = {
  "heavyBaseLetters": ["خ", "ص", "ض", "ط", "ظ", "غ", "ق"],
  "qalqalahLetters": ["ق", "ط", "ب", "ج", "د"],
  "sunLetters": ["ت", "ث", "د", "ذ", "ر", "ز", "س", "ش", "ص", "ض", "ط", "ظ", "ل", "ن"],
  "alifFollowerLetters": ["ا", "ى"],
  "noonTanweenTargetOnlyIdghamLetters": ["ن"],
  "noonTanweenSplitIdghamLetters": ["م", "ي", "و"],
  "noonTanweenSourceOnlyIdghamLetters": ["ل", "ر"],
  "ikhfaaHeavyLetters": ["ص", "ض", "ط", "ظ", "ق"],
  "ikhfaaLightLetters": ["ت", "ث", "ج", "د", "ذ", "ز", "س", "ش", "ف", "ك"],
};

String? colorForRule(String ruleId) => tajweedColors[ruleId];
